import type { Metadata } from 'next'
import './globals.css'
import { notoSansSC } from '@/ui/fonts'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' data-theme='winter' className={` ${notoSansSC.className} h-full antialiased`}>
			<body className='min-h-full flex flex-col gap-6 '>
				<main className='flex-1'>{children}</main>
			</body>
		</html>
	)
}
